# Generated by Django 3.2.9 on 2022-04-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150)),
                ('Char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q_A.characters')),
                ('Q_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q_A.questions')),
            ],
        ),
    ]
