# Generated by Django 3.2.9 on 2022-04-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0003_answers_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='Char',
        ),
    ]
