# Generated by Django 3.2.9 on 2022-05-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_A', '0005_answers_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='Char',
        ),
    ]
